### ISSUE TITLE
useFocusTrap focus can escape when clicking non-actionable nodes inside the modal.

### ISSUE THREAD

**Issue by hegelstad** [charlie-tango/hooks#24]
See attached screenrecording: https://i.vgy.me/PQ0Kiv.webm

Interesting parts:
0:39 - left click inside modal
0:40 - shift+tab
0:41 - focus has escaped modal

Other details:
 - It works as expected when pressing tab (without shift).
 - The same issue occurs if I press the backdrop when the modal should stay open on outside click.

**Comment by thebuilder** [comment]
That's weird. 
Can you make the example in a [Codesandbox](https://codesandbox.io)?

**Comment by thebuilder** [comment]
I've done a refactoring of the `useFocusTrap`, that also replaces the old `blur` and `focus` events with `focusin` and `focusout` - I think this might have solved this issue?
